//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CRMSync.AQIRSync {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback SaveContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAMDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::CRMSync.Properties.Settings.Default.CRMSync_AQIRSync_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveContactCompletedEventHandler SaveContactCompleted;
        
        /// <remarks/>
        public event SaveAddressCompletedEventHandler SaveAddressCompleted;
        
        /// <remarks/>
        public event DeleteContactCompletedEventHandler DeleteContactCompleted;
        
        /// <remarks/>
        public event DeleteAddressCompletedEventHandler DeleteAddressCompleted;
        
        /// <remarks/>
        public event UpdateAMDetailsCompletedEventHandler UpdateAMDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx/SaveContact", RequestNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", ResponseNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveContact(string StrXmlValue) {
            object[] results = this.Invoke("SaveContact", new object[] {
                        StrXmlValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveContactAsync(string StrXmlValue) {
            this.SaveContactAsync(StrXmlValue, null);
        }
        
        /// <remarks/>
        public void SaveContactAsync(string StrXmlValue, object userState) {
            if ((this.SaveContactOperationCompleted == null)) {
                this.SaveContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveContactOperationCompleted);
            }
            this.InvokeAsync("SaveContact", new object[] {
                        StrXmlValue}, this.SaveContactOperationCompleted, userState);
        }
        
        private void OnSaveContactOperationCompleted(object arg) {
            if ((this.SaveContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveContactCompleted(this, new SaveContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx/SaveAddress", RequestNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", ResponseNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveAddress(string StrXmlValue) {
            object[] results = this.Invoke("SaveAddress", new object[] {
                        StrXmlValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAddressAsync(string StrXmlValue) {
            this.SaveAddressAsync(StrXmlValue, null);
        }
        
        /// <remarks/>
        public void SaveAddressAsync(string StrXmlValue, object userState) {
            if ((this.SaveAddressOperationCompleted == null)) {
                this.SaveAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAddressOperationCompleted);
            }
            this.InvokeAsync("SaveAddress", new object[] {
                        StrXmlValue}, this.SaveAddressOperationCompleted, userState);
        }
        
        private void OnSaveAddressOperationCompleted(object arg) {
            if ((this.SaveAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAddressCompleted(this, new SaveAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx/DeleteContact", RequestNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", ResponseNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteContact(string strXmlValue) {
            object[] results = this.Invoke("DeleteContact", new object[] {
                        strXmlValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteContactAsync(string strXmlValue) {
            this.DeleteContactAsync(strXmlValue, null);
        }
        
        /// <remarks/>
        public void DeleteContactAsync(string strXmlValue, object userState) {
            if ((this.DeleteContactOperationCompleted == null)) {
                this.DeleteContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteContactOperationCompleted);
            }
            this.InvokeAsync("DeleteContact", new object[] {
                        strXmlValue}, this.DeleteContactOperationCompleted, userState);
        }
        
        private void OnDeleteContactOperationCompleted(object arg) {
            if ((this.DeleteContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteContactCompleted(this, new DeleteContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx/DeleteAddress", RequestNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", ResponseNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteAddress(string strXmlValue) {
            object[] results = this.Invoke("DeleteAddress", new object[] {
                        strXmlValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAddressAsync(string strXmlValue) {
            this.DeleteAddressAsync(strXmlValue, null);
        }
        
        /// <remarks/>
        public void DeleteAddressAsync(string strXmlValue, object userState) {
            if ((this.DeleteAddressOperationCompleted == null)) {
                this.DeleteAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAddressOperationCompleted);
            }
            this.InvokeAsync("DeleteAddress", new object[] {
                        strXmlValue}, this.DeleteAddressOperationCompleted, userState);
        }
        
        private void OnDeleteAddressOperationCompleted(object arg) {
            if ((this.DeleteAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAddressCompleted(this, new DeleteAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx/UpdateAMDetails", RequestNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", ResponseNamespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateAMDetails(string strXmlValue) {
            object[] results = this.Invoke("UpdateAMDetails", new object[] {
                        strXmlValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAMDetailsAsync(string strXmlValue) {
            this.UpdateAMDetailsAsync(strXmlValue, null);
        }
        
        /// <remarks/>
        public void UpdateAMDetailsAsync(string strXmlValue, object userState) {
            if ((this.UpdateAMDetailsOperationCompleted == null)) {
                this.UpdateAMDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAMDetailsOperationCompleted);
            }
            this.InvokeAsync("UpdateAMDetails", new object[] {
                        strXmlValue}, this.UpdateAMDetailsOperationCompleted, userState);
        }
        
        private void OnUpdateAMDetailsOperationCompleted(object arg) {
            if ((this.UpdateAMDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAMDetailsCompleted(this, new UpdateAMDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://localhost/CRMToAqirSyncService/CRMToAqirSyncService.asmx", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveContactCompletedEventHandler(object sender, SaveContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveAddressCompletedEventHandler(object sender, SaveAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteContactCompletedEventHandler(object sender, DeleteContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteAddressCompletedEventHandler(object sender, DeleteAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateAMDetailsCompletedEventHandler(object sender, UpdateAMDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAMDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAMDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591